fix: LIMIT_MAKER does not require timeInForce
Error: `{"code":-1106,"msg":"Parameter 'timeInForce' sent when not required."}`
API Docs: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#new-order--trade